### PR TITLE
Add changes requested for modularisation

### PR DESCRIPTION
**Pull request by PaulMansat**
- rename the model memory to “My Model Library”
- change "titanic model information" to "titanic task information"
- add Node version to the readme
- naming convention update (snake case)
- folder name (no space, respect the snake case convention)
- remove peers server from readme & add the new peer credentials (test with gcloud, martin m has set up credentials already)

### CODE REVIEW

**Review by mmilenkoski — APPROVED** [review]
Great job Paul, thanks for refactoring!

**Comment by martinjaggi** [comment]
can we merge this as it affects many files?

**Comment by PaulMansat** [comment]
> can we merge this as it affects many files?

There are many file changes because I renamed most variables to respect the camelCase convention 👍.

**Comment by mmilenkoski** [comment]
> > can we merge this as it affects many files?
> 
> There are many file changes because I renamed most variables and functions to respect the camelCase convention 👍. Only the variables used to access the database are snake_case.
> Most other modifications only impact few files.

That's correct, but it's still a good idea to merge this as soon as possible, so others can work on top of the refactored code. Do you plan to add anything else? If not, I think it's ready to be merged.

**Pull request merged**
