### PR TITLE
Add password protection for tasks

### PR DESCRIPTION
**Pull request by mmilenkoski**
This PR implements the client-side changes for #82. 

For this demo, I keep the password in the task information of the MNIST task. After #89 is merged, we can move to server-side authentication. 

Demo:

https://user-images.githubusercontent.com/10998465/123310626-9201d800-d526-11eb-87e9-fd90a295115b.mp4

### CODE REVIEW

**Review by martinjaggi — CHANGES_REQUESTED** [review]
we can make this a bit more secure, and without needing trust in any server.

whenever peers exchange a model, they also send the hash of `from-peer-id+" "+password`. the receiving peer then checks if this received hash is the same as what they would compute with what they think is the password. if not it will decline the update.
to initially let the user know if they have the right password or not, we check agains the hash of the password alone. this hash is publicly stored in the task definition.

the scheme above doesn't yet protect from peers imitating others or sybil attacks, but that can be solved in a later stage by adding authentification if necessary

this way others can't simply eavesdrop the password. does not prevent si

**Comment by martinjaggi** [comment]
we can for example use SHA256 from the library here: https://github.com/h2non/jshashes

**Comment by mmilenkoski** [comment]
hey @martinjaggi, I added your suggestions. Let me know what you think. I moved the password to titanic to test more easily. The hash is from the password `deai_titanic`

**Comment by mmilenkoski** [comment]
> should this function be called receive sth, or handle?

I think it is okay like this since it handles the data received by peerjs based on the type. We can change it if you think it would be better.

**Review by martinjaggi — APPROVED** [review]

**Pull request merged**
